name: Compile PDFs

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: texlive/texlive:latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set DATE env var
      run: |
        echo "DATE=$(date +%F)" >> $GITHUB_ENV
        echo "TAG=release-$(date +%F)" >> $GITHUB_ENV

    - name: Compile cv
      run: make cv.pdf

    - name: Compile resume
      run: make resume.pdf

    - name: Compile Cv-Resume.pdf
      run: make Cv-Resume.pdf


    - uses: actions/upload-artifact@v4
      with:
        name: Docs
        path: Docs/*.pdf

    - name: Rename PDFs with date
      run: |
        cp Docs/cv.pdf Docs/cv-${{ env.DATE }}.pdf
        cp Docs/resume.pdf Docs/resume-${{ env.DATE }}.pdf
        cp Docs/Cv-Resume.pdf Docs/Cv-Resume-${{ env.DATE }}.pdf
        

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.TAG }}
        files: |
          Docs/cv-${{ env.DATE }}.pdf
          Docs/resume-${{ env.DATE }}.pdf
          Docs/Cv-Resume-${{ env.DATE }}.pdf
          
